import cv2
import matplotlib.pyplot as plt

plt.figure()

i = cv2.imread("/Users/varun/documnents/deep_learning/learn_pytorch/gesture_detection/display/A.jpg")
i = cv2.cvtColor(i,cv2.COLOR_BGR2RGB)
plt.subplot(1,2,1)
plt.imshow(i)
plt.axis('off')
plt.title("A")
i = cv2.imread("display/B.jpg")
i = cv2.cvtColor(i,cv2.COLOR_BGR2RGB)
plt.subplot(1,2,2)
plt.imshow(i)
plt.axis('off')
plt.title("B")
plt.figure()
i = cv2.imread("display/C.jpg")
i = cv2.cvtColor(i,cv2.COLOR_BGR2RGB)
plt.subplot(1,2,1)
plt.imshow(i)
plt.axis('off')
plt.title("C")
i = cv2.imread("display/D.jpg")
i = cv2.cvtColor(i,cv2.COLOR_BGR2RGB)
plt.subplot(1,2,2)
plt.imshow(i)
plt.axis('off')
plt.title("D")

plt.figure()

i = cv2.imread("display/E.jpg")
i = cv2.cvtColor(i,cv2.COLOR_BGR2RGB)
plt.subplot(1,2,1)
plt.imshow(i)
plt.axis('off')
plt.title("E")

i = cv2.imread("display/F.jpg")
i = cv2.cvtColor(i,cv2.COLOR_BGR2RGB)
plt.subplot(1,2,2)
plt.imshow(i)
plt.axis('off')
plt.title("F")

plt.figure()
i = cv2.imread("display/G.jpg")
i = cv2.cvtColor(i,cv2.COLOR_BGR2RGB)
plt.subplot(1,2,1)
plt.imshow(i)
plt.axis('off')
plt.title("G")

i = cv2.imread("display/H.jpg")
i = cv2.cvtColor(i,cv2.COLOR_BGR2RGB)
plt.subplot(1,2,2)
plt.imshow(i)
plt.axis('off')
plt.title("H")

plt.figure()

i = cv2.imread("display/I.jpg")
i = cv2.cvtColor(i,cv2.COLOR_BGR2RGB)
plt.subplot(1,2,1)
plt.imshow(i)
plt.axis('off')
plt.title("I")

i = cv2.imread("display/J.jpg")
i = cv2.cvtColor(i,cv2.COLOR_BGR2RGB)
plt.subplot(1,2,2)
plt.imshow(i)
plt.axis('off')
plt.title("J")

plt.figure()
i = cv2.imread("display/K.jpg")
i = cv2.cvtColor(i,cv2.COLOR_BGR2RGB)
plt.subplot(1,2,1)
plt.imshow(i)
plt.axis('off')
plt.title("K")

i = cv2.imread("display/L.jpg")
i = cv2.cvtColor(i,cv2.COLOR_BGR2RGB)
plt.subplot(1,2,2)
plt.imshow(i)
plt.axis('off')
plt.title("L")

plt.figure()

i = cv2.imread("display/M.jpg")
i = cv2.cvtColor(i,cv2.COLOR_BGR2RGB)
plt.subplot(1,2,1)
plt.imshow(i)
plt.axis('off')
plt.title("M")

i = cv2.imread("display/N.jpg")
i = cv2.cvtColor(i,cv2.COLOR_BGR2RGB)
plt.subplot(1,2,2)
plt.imshow(i)
plt.axis('off')
plt.title("N")

plt.figure()
i = cv2.imread("display/O.jpg")
i = cv2.cvtColor(i,cv2.COLOR_BGR2RGB)
plt.subplot(1,2,1)
plt.imshow(i)
plt.axis('off')
plt.title("O")

i = cv2.imread("display/P.jpg")
i = cv2.cvtColor(i,cv2.COLOR_BGR2RGB)
plt.subplot(1,2,2)
plt.imshow(i)
plt.axis('off')
plt.title("P")

plt.figure()

i = cv2.imread("display/Q.jpg")
i = cv2.cvtColor(i,cv2.COLOR_BGR2RGB)
plt.subplot(1,2,1)
plt.imshow(i)
plt.axis('off')
plt.title("Q")

i = cv2.imread("display/R.jpg")
i = cv2.cvtColor(i,cv2.COLOR_BGR2RGB)
plt.subplot(1,2,2)
plt.imshow(i)
plt.axis('off')
plt.title("R")


plt.figure()
i = cv2.imread("display/S.jpg")
i = cv2.cvtColor(i,cv2.COLOR_BGR2RGB)
plt.subplot(1,2,1)
plt.imshow(i)
plt.axis('off')
plt.title("S")

i = cv2.imread("display/T.jpg")
i = cv2.cvtColor(i,cv2.COLOR_BGR2RGB)
plt.subplot(1,2,2)
plt.imshow(i)
plt.axis('off')
plt.title("T")

plt.figure()

i = cv2.imread("display/U.jpg")
i = cv2.cvtColor(i,cv2.COLOR_BGR2RGB)
plt.subplot(1,2,1)
plt.imshow(i)
plt.axis('off')
plt.title("U")

i = cv2.imread("display/V.jpg")
i = cv2.cvtColor(i,cv2.COLOR_BGR2RGB)
plt.subplot(1,2,2)
plt.imshow(i)
plt.axis('off')
plt.title("V")

plt.figure()
i = cv2.imread("display/W.jpg")
i = cv2.cvtColor(i,cv2.COLOR_BGR2RGB)
plt.subplot(1,2,1)
plt.imshow(i)
plt.axis('off')
plt.title("W")

i = cv2.imread("display/X.jpg")
i = cv2.cvtColor(i,cv2.COLOR_BGR2RGB)
plt.subplot(1,2,2)
plt.imshow(i)
plt.axis('off')
plt.title("X")

plt.figure()

i = cv2.imread("display/Y.jpg")
i = cv2.cvtColor(i,cv2.COLOR_BGR2RGB)
plt.subplot(1,2,1)
plt.imshow(i)
plt.axis('off')
plt.title("Y")

i = cv2.imread("display/Z.jpg")
i = cv2.cvtColor(i,cv2.COLOR_BGR2RGB)
plt.subplot(1,2,2)
plt.imshow(i)
plt.axis('off')
plt.title("Z")

plt.figure()
i = cv2.imread("display/del.jpg")
i = cv2.cvtColor(i,cv2.COLOR_BGR2RGB)
plt.subplot(1,2,1)
plt.imshow(i)
plt.axis('off')
plt.title("delete")